### ISSUE TITLE
Cross connectivity score 

### ISSUE THREAD

**Issue by ankitbioinfo** [prabhakarlab/Banksy_py#3]
Hello Developers, 

Thank you for providing spatial domain clustering tool BANKSY. I have a question about how to access the cross connectivity score matrix. After run the following command. 
plot_results(
    results_df,
    weights_graph,
    c_map,
    match_labels = True,
    coord_keys = coord_keys,
    max_num_labels  =  max_num_labels, 
    save_path = os.path.join(file_path, 'tmp_png'),
    save_fig = True, # save the spatial map of all clusters
    save_seperate_fig = True, # save the figure of all clusters plotted seperately
)

It generate 3 "connection between labels" heatmap matrix for (nonspatial, scaled gaussian nc 0.2, scaled gaussian nc 0.8) 
I have a two question first how to access these three matrix dataset from adata and 
second how to perform such scoring between the banksky labels and cell type annotation.

**Comment by vipulsinghal02** [comment]
Hi Ankit, 

Before I dive into explaining things, I want to clarify that the cluster connectivity score is *within* a  clustering result, not between two different clustering results. For a given spatial connectivity graph, we are computing how many of cell type $i$ are connected spatially to cells of cell type $j$. See the NCC score section in the BANKSY paper's methods. 

You will find the connections matrix you are looking for [here](https://github.com/prabhakarlab/Banksy_py/blob/10770c2ad707d34e0e4c07e61ea18baacf53b121/banksy/labels.py#L508). 

So for example, you can run code like this: 
```
    connections = interlabel_connections(label, weights_matrix)

    if zero_self_connections:
        np.fill_diagonal(connections, 0)
    elif normalize_by_self_connections:
        connections /= connections.diagonal()[:, np.newaxis]
```
Where you can choose your flag `zero_self_connections` or `normalize_by_self_connections` per your preferences. 

As for how the connection strength is calculated, consider the Plot Results section in the SlideSeqv1 [vignette](https://github.com/prabhakarlab/Banksy_py/blob/10770c2ad707d34e0e4c07e61ea18baacf53b121/slideseqv1_analysis.ipynb):

Here, we have 16 labels, and 17326 cells (as seen my the output `matrix multiplying labels x weights x labels-transpose ((16, 17326) x (17326, 17326) x (17326, 16))`, for example). 

A bit of explanation on how this product leads to the connections matrix: let $L$ be the $16 \times 17326$ one-hot encoding matrix of labels (i.e., in each column (spot or cell), only one row element is 1, corresponding to the label that that cell has been labeled with). Let $W$ be the $17326 \times 17326$ matrix of spatial graph connection weights. 

Then the connections matrix is defined $C \triangleq L W L^T$. Consider what the $(i, j)^\text{th}$ entry of this matrix is: it is the product of the $i$-th row of $L$, denoted $L(i, :)$, with the matrix $W$. The result then multiplied with the $j$-th column of $L^T$ (i.e., the column version of the $j$-th row of $L$, denoted $L(j, :)^T$). 

$L(i, :)$ has $1$'s for all the cells that have label $i$, and $0$ otherwise. Now you can reason through what the $(i, j)$-th entry of the product $L W L^T$ gives: the sum of all the weights o of the spatial connections between cells labeled $i$ with those labeled $j$.

**Comment by ankitbioinfo** [comment]
Hi Vipul, 

Many thanks for the detailed explanation. One question in following part 
```matrix multiplying labels x weights x labels-transpose ((16, 17326) x (17326, 17326) x (17326, 16)) ```
It is possible to change the label transpose matrix with some other labels for example 
```((16, 17326) x (17326, 17326) x (17326, 25))```
So that I can get ```16 x 25``` cells connectivity score.

**Comment by vipulsinghal02** [comment]
Hi Ankit, 

Yeah that should work. I think $C^{A,B} \triangleq L_A W L_B^T$, where $L_A$ and $L_A$ are the one hot encoding matrices of the two different (A and B) clustering results, *should* give you the cross connectivity score between the two clusterings you are looking for. Note this is not like an ARI. You are simply checking what the spatial adjacency relation between the two labelings is. I.e., $C^{A,B}_{i,j}$ is the total weight of the spatial adjacency of cells labeled $i$ in clustering $A$ and $j$ in clustering $B$ (including self connections). 

At least I *think* what I said is true. Maybe you can try it on a toy example. Code for how to generate the relevant matrices can be found [here](https://github.com/prabhakarlab/Banksy_py/blob/10770c2ad707d34e0e4c07e61ea18baacf53b121/banksy/labels.py#L467) (modify it to change $L$ to $L_A$ and $L_B$): 

```
    normalized_onehot = label.generate_normalized_onehot(verbose=False)

    print(
        f"\nmatrix multiplying labels x weights x labels-transpose "
        f"({normalized_onehot.shape} "
        f"x {weights_matrix.shape} "
        f"x {normalized_onehot.T.shape})\n"
    )

    connections = normalized_onehot @ weights_matrix @ normalized_onehot.T
```
